if(NOT TARGET depends::opencv)
    find_package(OpenCV REQUIRED)
    add_library(depends::opencv INTERFACE IMPORTED GLOBAL)
    target_include_directories(depends::opencv INTERFACE ${OpenCV_INCLUDE_DIRS})
    target_link_libraries(depends::opencv INTERFACE ${OpenCV_LIBS})
endif()
